# PyTorch Fundamentals
> A tutorial of PyTorch.

- toc: true 
- badges: true
- comments: true
- categories: [jupyter]
- image: images/chart-preview.png

## About
This notebook covers the PyTorch Fundamentals using the Zero to Mastery Learn PyTorch for Deep Learning guide.
Resource Link: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
!nvidia-smi

Thu Dec  1 12:24:52 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:2B:00.0  On |                  N/A |
| 30%   53C    P8    30W / 320W |    575MiB / 10240MiB |     17%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Topics to Cover
1. Introduction to tensors
2. Creating tensors
3. Getting information from tensors
4. Manipulating tensors
5. Indexing on tensors
6. Mixing PyTorch tensors and NumPy
7. PyTorch on GPU

### Importing PyTorch

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

/usr/local/lib/python3.8/dist-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


1.13.0+cu117


## Introduction to Tensors

A Tensor is an algebraic object that describes multilinear relationship between sets of algebraic objects related to a vector space.
> youtube: https://www.youtube.com/watch?v=f5liqUk0ZTw

### Creating Tensors

A [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html) is a multi-dimensional matrix containing elements of a single data type. There are various data types which can be defined. There are also `CPU` and `GPU` tensors.

#### Scalar

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# Check dimensions
scalar.ndim

0

In [5]:
# Get the Python number within a scalar tensor
scalar.item()

7

#### Vectors

In [6]:
# Vector
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [7]:
# Check dimensions
vector.ndim

1

In [8]:
# Check shape of vector
vector.shape

torch.Size([2])

#### Matrix

In [9]:
# Matrix
matrix = torch.tensor([[1,2],
                      [3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [10]:
# Check dimensions
matrix.ndim

2

In [11]:
# Check shape
matrix.shape

torch.Size([2, 2])

#### Tensors

In [12]:
# Tensor
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
# Check dimensions
tensor.ndim

3

In [14]:
# Check shape
tensor.shape

torch.Size([1, 3, 3])

The following image visually depicts the difference between scalars, vectors, matrix and tensors.
![](2022-11-28/00-scalar-vector-matrix-tensor.png)

### Random Tensors

A machine learning model often starts out with large random tensors and adjusts these random numbers as it works through the data to represent it in a better way. To do this in PyTorch we can use the [`torch.rand`](https://pytorch.org/docs/stable/generated/torch.rand.html) method.

In [15]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.3864, 0.4220, 0.3463, 0.1763],
         [0.3355, 0.9340, 0.2307, 0.6128],
         [0.0757, 0.9835, 0.4912, 0.1533]]),
 torch.float32)

In [16]:
# Create a random tensor of size (224,224,3)
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

Sometimes we just want to fill tensors with zeros or ones. We can do this using the [`torch.zeros()`](https://pytorch.org/docs/stable/generated/torch.zeros.html) or [`torch.ones()`](https://pytorch.org/docs/stable/generated/torch.ones.html) method.

In [17]:
# Create a tensor of all zeros
zeros_tensor = torch.zeros(size=(3,4))
zeros_tensor, zeros_tensor.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [18]:
# Create tensor of all ones
ones_tensor = torch.ones(size=(3,4))
ones_tensor, ones_tensor.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Creating a range and tensors like

To create a range of numbers we can use [`torch.arange(start, end, step)`](https://pytorch.org/docs/stable/generated/torch.arange.html).

In [19]:
# Use torch.arange()
zero_to_ten = torch.arange(start=0,end=10,step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

To mimic a shape of another tensor we can use [`torch.rand_like(input)`](https://pytorch.org/docs/stable/generated/torch.rand_like.html), [`torch.zeros_like(input)`](https://pytorch.org/docs/stable/generated/torch.zeros_like.html) or [`torch.ones_like(input)`](https://pytorch.org/docs/stable/generated/torch.ones_like.html).

In [20]:
# Create a tensor similar to zeros_tensor but using random
rand_zeros_tensor_like = torch.rand_like(zeros_tensor)
rand_zeros_tensor_like, rand_zeros_tensor_like.dtype

(tensor([[0.6870, 0.7167, 0.6738, 0.9651],
         [0.1833, 0.4796, 0.7711, 0.6932],
         [0.2788, 0.0643, 0.0418, 0.5420]]),
 torch.float32)

## Getting Information from Tensors

The most common attributes of tensors are `shape`, `dtype` and `device`.

In [21]:
# Create a tensor
some_tensor = torch.rand(size=(3,4))

# Display details of tensor
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.0452, 0.0207, 0.7986, 0.6861],
        [0.4294, 0.7774, 0.5604, 0.4319],
        [0.1340, 0.9240, 0.3545, 0.6204]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Manipulating Tensors (operations)

One of the most important tensor operations in deep learning is matrix multiplication.

In [22]:
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [23]:
# Element-wise matrix multiplicaiton
tensor * tensor

tensor([1, 4, 9])

In [24]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

## Indexing

How do we access specific data from tensors?

In [25]:
some_tensor = torch.arange(start=1, end=10).reshape(1, 3, 3)
some_tensor, some_tensor.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [26]:
# Indexing bracket by bracket
print(f"First square bracket: {some_tensor[0]}")
print(f"Second square bracket: {some_tensor[0][0]}")
print(f"Third square bracket: {some_tensor[0][0][0]}")

First square bracket: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [27]:
# Selecting first row
print(f"First row of tensor: {some_tensor[:,0]}")

First row of tensor: tensor([[1, 2, 3]])


In [28]:
# Selecting second column
print(f"Second column of tensor: {some_tensor[:,:,1]}")

Second column of tensor: tensor([[2, 5, 8]])


In [29]:
# Select bottom 2x2
print(f"Selecting bottom right 2x2 grid: {some_tensor[:,1:,1:]}")

Selecting bottom right 2x2 grid: tensor([[[5, 6],
         [8, 9]]])


## PyTorch and NumPy

PyTorch has built in functionality to convert NumPy arrays into PyTorch tensors. This is done using the `torch.from_numpy(ndarray)` method. To convert a Tensor to an array we can use `torch.Tensor.numpy()`.

In [30]:
# Converting array to tensor
array = np.random.rand(3,3)
array, torch.from_numpy(array)

(array([[0.52877635, 0.51487637, 0.28748219],
        [0.03840897, 0.40011216, 0.7600652 ],
        [0.65834844, 0.06947759, 0.87114052]]),
 tensor([[0.5288, 0.5149, 0.2875],
         [0.0384, 0.4001, 0.7601],
         [0.6583, 0.0695, 0.8711]], dtype=torch.float64))

In [31]:
# Converting tensor to array
some_tensor = torch.rand(size=(3,3))
some_tensor, some_tensor.numpy()

(tensor([[0.1617, 0.9384, 0.5670],
         [0.3329, 0.2371, 0.1353],
         [0.7492, 0.9597, 0.1461]]),
 array([[0.1617378 , 0.9383805 , 0.5670012 ],
        [0.3328787 , 0.23712236, 0.13531995],
        [0.7492051 , 0.9597247 , 0.14605427]], dtype=float32))

## PyTorch on GPU

In [32]:
# Check for GPU
torch.cuda.is_available()

True

In [33]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [34]:
# Count number of devices
torch.cuda.device_count()

1

PyTorch maintains a seperation of where tensors are stored. If we are using GPUs for training then we have to put the tensors on the gpu device. This allows us to run faster numerical computation than using a CPU.

In [35]:
# Create tensor
some_tensor = torch.ones(size=(3,3))

# Move the tensor to GPU
tensor_on_gpu = tensor.to(device)

# Check where the tensor exists
print(tensor, tensor.device)

# Check where the tensor exists
print(tensor_on_gpu, tensor_on_gpu.device)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0') cuda:0


To move the tensor back to CPU we can use `torch.to('cpu')`. This is needed if we want to convert our tensor into a numpy array.

## Exercises 

1. Create a random tensor with shape `(7, 7)`.

In [36]:
torch.rand(size=(7,7))

tensor([[0.2939, 0.0436, 0.6219, 0.6090, 0.0334, 0.9435, 0.1173],
        [0.0818, 0.6880, 0.7191, 0.8980, 0.3537, 0.1512, 0.4098],
        [0.9492, 0.9181, 0.6112, 0.0101, 0.9554, 0.4541, 0.3899],
        [0.2519, 0.8227, 0.8853, 0.8640, 0.9598, 0.2262, 0.0393],
        [0.4030, 0.5945, 0.6027, 0.6424, 0.8491, 0.8344, 0.0452],
        [0.2884, 0.2951, 0.8422, 0.9204, 0.8882, 0.1274, 0.8725],
        [0.1320, 0.8361, 0.7701, 0.8724, 0.7167, 0.5192, 0.1237]])

2. Perform a matrix multiplication on the tensor from the previous problem with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [38]:
tensor_1 = torch.rand(size=(7,7))
tensor_2 = torch.rand(size=(1,7))

print(tensor_1.shape, tensor_2.shape)

torch.matmul(tensor_1, tensor_2.T)

torch.Size([7, 7]) torch.Size([1, 7])


tensor([[2.2379],
        [2.9939],
        [3.8932],
        [3.3609],
        [2.9280],
        [2.7368],
        [1.4672]])